import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case chinese = "zh-Hans"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }
}

enum L10n {
    static func text(_ key: String, _ language: AppLanguage) -> String {
        guard language == .chinese else { return key }
        return zhHans[key] ?? key
    }

    private static let zhHans: [String: String] = [
        "Health": "状态",
        "Sessions": "会话",
        "Repair": "修复",
        "Configure": "配置",
        "Backups": "备份",
        "Settings": "设置",
        "Logs": "日志",
        "Claude Code session repair": "Claude Code 会话修复",
        "Backend error": "后端错误",
        "OK": "确定",
        "Refresh": "刷新",
        "Language": "语言",
        "Check local paths, provider state, and route readiness.": "检查本机路径、供应商状态和路由准备情况。",
        "Pick the transcript that needs repair.": "选择需要修复的对话记录。",
        "Preview exactly what will change before writing.": "写入前预览具体改动。",
        "Apply MiMo route and Claude memory guardrails.": "应用 MiMo 路由和 Claude 记忆保护规则。",
        "Restore files created by repair or configure actions.": "恢复修复或配置操作创建的备份文件。",
        "Inspect backend discovery and local paths.": "查看后端发现的本地路径。",
        "Review current app state and action summaries.": "查看当前应用状态和操作摘要。",
        "Create full chat backup?": "要创建聊天记录全量备份吗？",
        "Create Full Backup": "创建全量备份",
        "This copies Claude chat records locally before later repairs or configuration changes. The app has no network upload or telemetry and does not collect private data.": "这会在后续修复或配置前，把 Claude 聊天记录复制到本地备份目录。本软件没有联网上传和遥测功能，不会采集隐私数据。",
        "Local only, no data collection": "仅本地操作，不采集隐私",
        "No full chat backup": "未做全量备份",
        "Full backup ready": "全量备份已完成",
        "Full backup created": "全量备份已创建",
        "Full backup recommended": "建议先全量备份",
        "Full Backup": "全量备份",
        "Full backup": "全量备份",
        "Backing up": "备份中",
        "files": "个文件",
        "Full session backup created.": "聊天记录全量备份已创建。",
        "Setup": "环境",
        "Start here": "从这里开始",
        "Recommended first-run flow": "推荐首次配置流程",
        "Each step shows what it will read or write before you press a button. The one-click setup performs steps 2 and 3 with backups.": "每一步都会在你点击前说明会读取或写入什么；一键配置只执行第 2、3 步，并会先创建备份。",
        "Start with a full local chat backup, then configure routes, memory, and repair only dangerous sessions.": "先创建本地聊天记录全量备份，再配置路由和记忆，最后只处理危险会话。",
        "Use the recommended setup first, then review warning sessions only when they contain embedded media or base64.": "先使用推荐配置；之后只有会话包含嵌入媒体或 base64 时才需要清理。",
        "Open Configure": "打开配置",
        "One-click Recommended Setup": "一键推荐配置",
        "Apply recommended setup?": "要应用推荐配置吗？",
        "This sets Haiku to MiMo 2.5, keeps main work on MiMo Pro, and writes the managed memory block at the end of Claude memory.": "这会把 Haiku 设为 MiMo 2.5，主任务保持 MiMo Pro，并把托管记忆规则写到 Claude 记忆文件末尾。",
        "Check paths": "检查路径",
        "Full chat backup": "聊天记录全量备份",
        "Copies Claude projects and sessions into a local backup folder.": "把 Claude 的 projects 和 sessions 聊天记录目录复制到本地备份文件夹。",
        "Local only: no network upload, no telemetry, and no private data collection.": "仅本地操作：不联网上传、无遥测、不会采集隐私数据。",
        "Create Backup": "创建备份",
        "No files are changed.": "不会修改任何文件。",
        "Reads local Claude, CC Switch, provider, and memory paths so the app knows what is available.": "只读取本机 Claude、CC Switch、供应商和记忆路径，用来判断当前环境是否可用。",
        "Check Now": "立即检查",
        "Not checked yet": "未检查",
        "All paths look good": "路径都没问题",
        "Some paths need review": "有路径需检查",
        "Route needs update": "路由待配置",
        "Route configured": "路由已配置",
        "Memory needs sync": "记忆待同步",
        "Memory rule synced": "记忆已同步",
        "No sessions checked yet": "未检查会话",
        "No dangerous sessions": "没有危险会话",
        "Dangerous sessions found": "发现危险会话",
        "Confirm Claude and CC Switch are detected.": "确认已识别 Claude 和 CC Switch。",
        "Set route": "设置路由",
        "Set model route": "设置模型路由",
        "Configure route and memory": "配置路由和记忆",
        "Writes CC Switch route and Claude memory only after backup/confirmation.": "只会在备份/确认后写入 CC Switch 路由和 Claude 记忆。",
        "MiMo 2.5 handles image work through the helper slot; main work stays on MiMo Pro.": "MiMo 2.5 通过助手槽位处理图片任务；主任务继续走 MiMo Pro。",
        "Route and memory ready": "路由和记忆已完成",
        "Route or memory needs setup": "路由或记忆待配置",
        "Writes only the current CC Switch provider route after creating a backup.": "先创建备份，然后只写入当前 CC Switch 供应商的模型路由。",
        "Main, Sonnet, and Opus stay on MiMo Pro; the helper slot can be set to MiMo 2.5.": "Main、Sonnet、Opus 保持 MiMo Pro；助手槽位可设置为 MiMo 2.5。",
        "Configure Route": "配置路由",
        "Route image helper to MiMo 2.5.": "把图片助手路由到 MiMo 2.5。",
        "Sync memory": "同步记忆",
        "Sync memory rule": "同步记忆规则",
        "Writes a managed block at the end of Claude memory after creating a backup.": "先创建备份，然后把托管规则写到 Claude 记忆文件末尾。",
        "The rule tells Claude to send image or drawing work through the helper model you chose.": "这条规则会告诉 Claude：图片或绘画任务走你选择的助手模型。",
        "Configure Memory": "配置记忆",
        "Write the managed rule at the end.": "把托管规则写到文件末尾。",
        "Review sessions": "检查会话",
        "Review dangerous sessions": "检查危险会话",
        "Preview is read-only; repair writes only after you confirm and a backup is created.": "预览是只读的；修复只有在你确认并创建备份后才会写入。",
        "Danger means embedded media/base64 or huge transcript. Warning often only means image path mentions.": "危险表示嵌入媒体/base64 或记录文件过大；警告通常只是提到了图片路径。",
        "Clean only embedded media/base64.": "只清理嵌入媒体/base64。",
        "Overview": "总览",
        "Claude": "Claude",
        "Provider": "供应商",
        "Risky sessions": "风险会话",
        "Dangerous sessions": "危险会话",
        "Ready": "就绪",
        "Needs review": "需检查",
        "Blocked": "已阻塞",
        "Unknown": "未知",
        "Not found": "未找到",
        "MiMo route": "MiMo 路由",
        "Main work stays on Pro; image helper requests route to 2.5.": "主任务保留在 Pro；图片辅助请求路由到 2.5。",
        "Changes pending": "有待应用的改动",
        "Already configured": "已配置",
        "Run health check to load route details.": "运行状态检查以加载路由详情。",
        "Main": "主模型",
        "Sonnet": "Sonnet",
        "Opus": "Opus",
        "Haiku": "Haiku",
        "Recent sessions": "最近会话",
        "Sessions with media blocks, base64 risk, or image path mentions.": "包含媒体块、base64 风险或图片路径提及的会话。",
        "No sessions loaded yet.": "尚未加载会话。",
        "Open Sessions": "打开会话",
        "Discovered paths": "发现的路径",
        "Used by the backend to find Claude Code and CC Switch.": "后端用这些路径定位 Claude Code 和 CC Switch。",
        "Claude home": "Claude 主目录",
        "Memory": "记忆",
        "CC Switch DB": "CC Switch 数据库",
        "Tool config": "工具配置",
        "No discovery report loaded.": "尚未加载发现报告。",
        "Memory rule": "记忆规则",
        "A managed instruction that tells Claude Code how to delegate image work.": "用于告诉 Claude Code 如何委托图片工作的托管指令。",
        "Missing or stale": "缺失或过期",
        "Installed": "已安装",
        "Review": "查看",
        "Target": "目标",
        "No memory preview loaded.": "尚未加载记忆预览。",
        "Risk": "风险",
        "All": "全部",
        "Ok": "正常",
        "Warning": "警告",
        "Danger": "危险",
        "Search project or session ID": "搜索项目或会话 ID",
        "Reload": "重新加载",
        "Loading sessions": "正在加载会话",
        "No matching sessions.": "没有匹配的会话。",
        "No sessions loaded yet. Click Reload or wait for refresh.": "尚未加载会话。请点重新加载，或等待自动刷新完成。",
        "No matching sessions. Clear search or choose another risk filter.": "没有匹配的会话。请清空搜索，或切换风险筛选。",
        "Filter warning sessions, select one, then repair on the right.": "筛选警告会话，在左侧选择，然后在右侧处理。",
        "Filter dangerous sessions first, select one, then repair on the right.": "默认先筛选危险会话，在左侧选择，然后在右侧处理。",
        "Usually image path mentions or moderate transcript size. It may need no transcript repair.": "通常只是提到了图片路径，或会话略大；不一定需要修复记录文件。",
        "Embedded media/base64 or a very large transcript. Preview before repair.": "通常是嵌入媒体/base64，或记录文件很大；修复前必须先预览。",
        "Session detail": "会话详情",
        "Preview repair before any file is changed.": "修改任何文件前先预览修复。",
        "Session": "会话",
        "Transcript": "记录文件",
        "Project": "项目",
        "Updated": "更新时间",
        "Messages": "消息数",
        "Image paths": "图片路径",
        "Media/base64": "媒体/base64",
        "Reasons": "原因",
        "Preview Repair": "预览修复",
        "Copy Session ID": "复制会话 ID",
        "Reveal Transcript": "在 Finder 中显示记录",
        "Select a session to inspect.": "选择一个会话查看详情。",
        "Repair workspace": "修复工作台",
        "Select a session on the left, preview changes, then apply with backup.": "在左侧选择会话，预览改动，再带备份应用。",
        "Path warning only": "仅路径警告",
        "Repair target": "修复目标",
        "Choose a cleanup mode, preview changes, then apply with backup.": "选择清理模式，预览改动，然后带备份应用。",
        "Mode": "模式",
        "Placeholder": "占位替换",
        "Strip media": "移除媒体",
        "Quarantine turn": "隔离轮次",
        "Preview": "预览",
        "Apply Repair": "应用修复",
        "Apply session repair?": "要应用会话修复吗？",
        "Apply with Backup": "创建备份并应用",
        "Cancel": "取消",
        "The backend will create a backup before writing the cleaned transcript.": "后端会在写入清理后的记录前创建备份。",
        "Select a session from Sessions first.": "请先从会话页选择一个会话。",
        "Preview changes": "预览改动",
        "Line-level changes detected by the backend.": "后端检测到的逐行改动。",
        "No media blocks need cleanup.": "没有需要清理的媒体块。",
        "Line": "行",
        "bytes": "字节",
        "No preview yet.": "尚未预览。",
        "Safety": "安全",
        "Repair writes only after a preview and creates a restorable backup.": "修复只会在预览后写入，并创建可恢复备份。",
        "Changes": "改动数",
        "Backup required": "需要备份",
        "Applied": "已应用",
        "Backup": "备份",
        "Yes": "是",
        "No": "否",
        "Preview is read-only.": "预览是只读操作。",
        "Apply requires explicit confirmation.": "应用需要明确确认。",
        "Restore is available from Backups.": "可以从备份页恢复。",
        "CC Switch route": "CC Switch 路由",
        "Update the current provider environment values.": "更新当前供应商的环境变量值。",
        "Edit each Claude model route separately.": "分别编辑每个 Claude 模型路由。",
        "Image model": "图片模型",
        "Image helper slot": "图片助手槽位",
        "Helper slot": "助手槽位",
        "Set 2.5 to helper": "将 2.5 设为助手",
        "Image helper": "图片助手",
        "Model name": "模型名",
        "Use 2.5": "使用 2.5",
        "Apply This": "应用此项",
        "Apply All Routes": "应用全部路由",
        "Apply Routes + Memory": "应用路由并同步记忆",
        "Apply Custom Routes + Memory": "应用自定义路由并同步记忆",
        "Apply model route?": "要应用模型路由吗？",
        "This writes only the selected CC Switch model route after creating a backup.": "这会先创建备份，然后只写入选中的 CC Switch 模型路由。",
        "This writes the selected CC Switch route and syncs memory when the image helper route is changed.": "这会写入选中的 CC Switch 路由；如果改的是图片助手路由，会同步写入记忆规则。",
        "Apply Route": "应用路由",
        "Apply CC Switch route?": "要应用 CC Switch 路由吗？",
        "This writes the current CC Switch provider configuration after creating a backup.": "这会先创建备份，然后写入当前 CC Switch 供应商配置。",
        "Route preview is not loaded.": "尚未加载路由预览。",
        "Recommended route": "推荐路由",
        "Normal use: put image and drawing requests on Haiku with MiMo 2.5.": "普通使用：把图片和绘画请求放到 Haiku 槽位，并使用 MiMo 2.5。",
        "Put MiMo 2.5 into Haiku": "把 MiMo 2.5 放到 Haiku",
        "This is the recommended setup for most users. Main work stays on MiMo Pro; image and drawing work uses the lighter Haiku helper slot.": "这是大多数用户推荐的配置。主任务仍走 MiMo Pro；图片和绘画任务走更轻的 Haiku 助手槽位。",
        "Apply 2.5 to Haiku": "应用 2.5 到 Haiku",
        "Apply 2.5 to Helper": "应用 2.5 到助手槽位",
        "Custom": "自定义",
        "Advanced model slots. Use this only if you want to route each Claude model separately.": "高级模型槽位。只有需要分别调整每个 Claude 模型时才需要改这里。",
        "Claude memory": "Claude 记忆",
        "Install the managed image routing instruction.": "安装托管图片路由指令。",
        "Sync the managed image routing instruction with the selected helper slot.": "让托管图片路由指令与选中的助手槽位同步。",
        "Keeps Claude aware of the selected image helper model.": "让 Claude 记住当前选择的图片助手模型。",
        "Claude should not read image or binary files directly because that can freeze the conversation. The helper reads or OCRs them first, then returns text.": "不要让 Claude 直接读取图片或二进制文件，因为这可能把对话卡死；助手会先读取/OCR 成文本，再把文本返回。",
        "Memory file": "记忆文件",
        "Block at end": "位于末尾",
        "Managed block will be removed.": "托管区块将被移除。",
        "Preview Memory": "预览记忆",
        "Reset": "复位",
        "Reset Memory Rule": "复位记忆规则",
        "Apply Memory Rule": "应用记忆规则",
        "Apply Claude memory rule?": "要应用 Claude 记忆规则吗？",
        "This writes a managed block to the Claude memory file after creating a backup.": "这会先创建备份，然后向 Claude 记忆文件写入托管区块。",
        "This writes the managed block at the end of the Claude memory file after creating a backup.": "这会先创建备份，然后把托管区块写到 Claude 记忆文件末尾。",
        "Reset Claude memory rule?": "要复位 Claude 记忆规则吗？",
        "Reset with Backup": "创建备份并复位",
        "This removes only the cc-mimo-rescue managed block after creating a backup.": "这会先创建备份，然后只移除 cc-mimo-rescue 托管区块。",
        "Memory preview is not loaded.": "尚未加载记忆预览。",
        "Before": "之前",
        "After": "之后",
        "Not set": "未设置",
        "Files created before repair, configuration, or memory writes.": "修复、配置或写入记忆前创建的文件备份。",
        "No backups found.": "没有找到备份。",
        "Restore": "恢复",
        "Restore backup?": "要恢复备份吗？",
        "the selected backup": "所选备份",
        "Unknown path": "未知路径",
        "This restores the original file recorded for": "这会恢复记录在备份中的原始文件：",
        "Read-only in this MVP. The backend auto-discovers local paths.": "当前 MVP 中为只读。后端会自动发现本地路径。",
        "Claude binary": "Claude 可执行文件",
        "Projects": "项目",
        "CC Switch home": "CC Switch 主目录",
        "Config": "配置",
        "Run Health refresh to load settings.": "刷新状态页以加载设置。",
        "A compact app-side view of recent state.": "当前应用状态的简要视图。",
        "Last action": "最近操作",
        "Loaded sessions": "已加载会话",
        "Loaded backups": "已加载备份",
        "Selected session": "所选会话",
        "None": "无",
        "Object": "对象",
        "List": "列表",
        "Repair applied. Backup created.": "修复已应用，备份已创建。",
        "Recommended setup applied.": "推荐配置已应用。",
        "Route updated.": "路由已更新。",
        "Memory rule updated.": "记忆规则已更新。",
        "Memory rule reset.": "记忆规则已复位。",
        "Backup restored.": "备份已恢复。",
        "Copy": "复制",
        "Reveal in Finder": "在 Finder 中显示",
        "Preview repair": "预览修复",
        "Image path mentions": "图片路径提及",
        "Media/base64 risk": "媒体/base64 风险",
        "Unknown project": "未知项目",
        "media blocks": "媒体块",
        "base64 risks": "base64 风险",
        "image path mentions": "图片路径提及",
        "large transcript": "大型记录",
        "This warning came from image path mentions. There are no embedded media/base64 blocks to clean.": "这个警告来自图片路径提及；会话里没有嵌入的媒体/base64 块需要清理。"
    ]
}
